### ISSUE TITLE
Altus window stays invisible (win10 fast ring)

### ISSUE THREAD

**Issue by nikopen** [amanharwara/altus#100]
App starts normally, it's in both tray and taskbar but the Altus window never shows in the desktop. Only by continuously clicking on the taskbar icon it shows for a split second before it disappears again. May be related to latest Windows Insider fast ring releases but issue has been there for at least a year. Running latest version. Other Electron apps run fine.

Any ideas or diagnostics? Something unusual used for UI/window other than Electron?

**Comment by amanharwara** [comment]
> Something unusual used for UI/window other than Electron?

I don't think so. It's just a regular Electron window.

What's the last version that works for you?

**Comment by nikopen** [comment]
3.4.1 works, 3.5.0 is broken

theme manager stuff from that version probably conflicted with saved theme settings or something.  
deleted appdata/roaming/altus and 3.5.0 runs fine, latest one too

**Comment by amanharwara** [comment]
If the latest version (3.18.0) works for you, please mark this issue as closed. If there are any other problems let me know

**Comment by AndreWinkels** [comment]
Any update on this. I am experiencing the same issue on my side. Have been using Altus without any issues since 2020/07. Now suddenly I can't maximise the app. It opens fine in Taskbar etc. and if I mouse over it in the taskbar I can even see when there are messages, but I just can't maximise the screen. I have already updated to the latest version... 3.18.0 

Let me know if you need anything else to troubleshoot this issue.
Thanks

**Comment by amanharwara** [comment]
@AndreWinkels I'm not sure exactly what could be causing this issue. Can you try opening `%appdata%/Altus` in Explorer, deleting all the files inside and then starting Altus?

**Comment by AndreWinkels** [comment]
Hi amanharwara

This issue seems to have resolved itself. 

Thanks for the quick response.

Andre
