### ISSUE TITLE
New feature to be considered: Autoreply feature

### ISSUE THREAD

**Issue by tanmaysri** [amanharwara/altus#105]
1. Auto reply to messages
2. next level could be to provide a chat bot feature like WATI

**Comment by amanharwara** [comment]
I'm staying away from auto-reply/chatbot features because of two reasons:

1. It is a way too much effort to maintain and breaks too often. I've tried implementing stuff like this before.
2. It might make WhatsApp target this app as they're not too fond of allowing stuff like this, at the very least in the past. I know this is relatively low risk but it's not one I'm willing to take for a feature that is niche.

If you feel like implementing it, please go ahead and do it. Altus is licensed under GPL-3 and as long as you keep your fork completely open-source and under the same license, you are free to do what you want with the code.
