### ISSUE TITLE
How do I make a custom theme with css for atlus?

### ISSUE THREAD

**Issue by sheeepdev** [amanharwara/altus#129]
You state in the readme: Custom Theme Support: Write your own CSS theme for WhatsApp. I can't find a way to write my own css, or even open developer tools to see the css classes, can you help me out?

**Comment by amanharwara** [comment]
Since the re-write, I haven't implemented a UI for using CSS instead of the Theme Creator. Not sure when or if I will do that. It is still possible to use CSS if you want, by editing the `themes.json` file manually.

As for the dev tools, those can be used if you run Altus in development mode, i.e. by cloning this repo and using `yarn start` in the Altus directory.

**Comment by sheeepdev** [comment]
> 
> 
> Since the re-write, I haven't implemented a UI for using CSS instead of the Theme Creator. Not sure when or if I will do that. It is still possible to use CSS if you want, by editing the `themes.json` file manually.
> 
> As for the dev tools, those can be used if you run Altus in development mode, i.e. by cloning this repo and using `yarn start` in the Altus directory.

i downgraded to 3.25 because of #125, does 3.25 support this, or what other version does support editing css?

**Comment by amanharwara** [comment]
I think the last version that has the UI for that is v3.20.0. You could try using that.
I removed it because I guessed barely anyone was using it and I didn't get any mention of it after I removed it either.
Might add it back whenever I get the time to work on Altus, but no guarantees for now at least.

**Comment by amanharwara** [comment]
The next version (v4.1.0) will have devtools and an option to use CSS while creating a theme instead of colors.

**Comment by sheeepdev** [comment]
> 
> 
> The next version (v4.1.0) will have devtools and an option to use CSS while creating a theme instead of colors.

Thanks so much, that will be perfect for me. Wanna change every detail :)

**Comment by amanharwara** [comment]
> @amanharwara also, unrelated to this issue but will u get to solve #125 ? I just love that status bar and it would be so good to switch to custom css but i would miss the custom titlebar

Yes, I'm going to start working on it soon, but I can't guarantee how soon I'll be able to finish it.

**Comment by sheeepdev** [comment]
> 
> 
> > @amanharwara also, unrelated to this issue but will u get to solve #125 ? I just love that status bar and it would be so good to switch to custom css but i would miss the custom titlebar
> 
> Yes, I'm going to start working on it soon, but I can't guarantee how soon I'll be able to finish it.

That would be amazing!

hyped up for 4.1.0 😄

**Comment by amanharwara** [comment]
[v4.1.0](https://github.com/amanharwara/altus/releases/tag/4.1.0) implements both the DevTools options and Custom CSS. Check it out.

**Comment by sheeepdev** [comment]
> 
> 
> [v4.1.0](https://github.com/amanharwara/altus/releases/tag/4.1.0) implements both the DevTools options and Custom CSS. Check it out.

Amazing, thanks a lot for this :)

**Comment by amanharwara** [comment]
@sheeepdev https://github.com/amanharwara/altus/issues/125#issuecomment-811003873
