### ISSUE TITLE
Permanent hint to activate Crome or to use firefox

### ISSUE THREAD

**Issue by dr-achenbach** [amanharwara/altus#135]
Every time I start Altus there is a popup that indicates "WhatsApp is funcitoning with Crome 60+... or use firefox..."
I don't use Crome but have firefox with newest version. So what ist this boring popup? In addition, mostly every time I open one of the 3 WhatsApp accounts there will be the announcement of an update. Why the hell so frequently?

I'm prepared to give a reasonable donation to have a Altus version without boring popups ;-)

Thanks in anticipation.

Kind regards
Friedhelm Achenbach
Königswinter, Germany

**Comment by amanharwara** [comment]
What version of Altus are you using?

**Comment by amanharwara** [comment]
> I don't use Crome but have firefox with newest version. So what ist this boring popup?

WhatsApp Web checks to see if you are using the latest version of Chrome & Firefox. It does this by checking the [User agent](https://en.wikipedia.org/wiki/User_agent) of the browser. Since they are very specific about the User agent, it will incorrectly flag Altus or similar applications as unsupported. This is fixed in the latest versions of Altus.

> In addition, mostly every time I open one of the 3 WhatsApp accounts there will be the announcement of an update. Why the hell so frequently?

I'm not sure why this is happening, to be honest. I've tried before to see what could be causing this but haven't found anything.

**Comment by dr-achenbach** [comment]
I Update any time, I'm asked to do so, i.e. mostly every day!

Am 26. März 2021 17:06:22 schrieb Aman Harwara ***@***.***>:

**Comment by amanharwara** [comment]
> I Update any time, I'm asked to do so, i.e. mostly every day!

From what I've seen, clicking the Update button in WhatsApp doesn't really do anything other than closing that popup.

What version of Altus are you using? (This can be found by clicking the `About` menu item.)

**Comment by amanharwara** [comment]
This has been fixed for a while now. If you're using an older version, please update to the [latest release](https://github.com/amanharwara/altus/releases/tag/4.8.1).
