### ISSUE TITLE
Nothing happened anymore? altus is dead?

### ISSUE THREAD

**Issue by tentaurus** [amanharwara/altus#190]
**Describe the bug**
A clear and concise description of what the bug is:

**To Reproduce**

1.

**Expected behavior**
A clear and concise description of what you expected to happen:

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Information:**
Version Info (Go to About > About and click "Copy Version Info"):

**Additional context**

**Comment by Fidelity88** [comment]
Instead of being so negative, maybe **help the developer by making a donation to motivate him**.

If you like the project, support it. I made a donation last month for this exact reason, because I use the software daily and want to thank and both motivate the developer to continue his awesome work.

**Comment by amanharwara** [comment]
The project is not dead, but it has become less of a priority because I rarely use WhatsApp and Altus anymore. I'm assuming this question is being asked because of the lack of progress about the "Update Chrome" issue or the multi-device beta not working. The thing with that is the solution for either one of those seems to break the other. I also haven't been able to replicate either of the issues now because it works just fine for me every time. That's why I've created the "Help Wanted" issue so that somebody else can try and fix it.

Anyways, apart from those two issues, there's not much that I think that needs to be added or fixed, which is also why new releases are less frequent. And unless I think of a new feature to add or am able to fix the two big issues, there's not going to be many releases. Maybe a few releases here and there for dependency updates.
