### ISSUE TITLE
Hello amanharwara,

### ISSUE THREAD

**Issue by Matse1968** [amanharwara/altus#192]
**Describe the bug**
A clear and concise description of what the bug is:

**To Reproduce**

1.

**Expected behavior**
A clear and concise description of what you expected to happen:

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Information:**
Version Info (Go to About > About and click "Copy Version Info"):

**Additional context**

**Comment by amanharwara** [comment]
Umm, what is the actual issue here?

**Comment by Matse1968** [comment]
Thank you so much for your E-Mail Aman,

it was the first time that I entered on that platform on search of a
solution. Tried to get in touch with you, but did´nt work.
I love Altus since a long time, as I can use it for 2 WhatsApp accounts at
the same time.
Since a short time, I´ve a huge problem and no idea how to solve it. I
guess, it appeared since an update or so. But even by re-installing older
versions... nothing works.

To describe what´s happening:
After installing everything works well and I can connect to my 2 WhatsApp
accounts of the mobile.
But if I switch of Altus or the computer.. next time starting, it does not
re-open again.
First thing that always appears is this:
[image: image.png]
It´s saying in my mother tongue (German) that I should update my Google
Chrome Version.
But verifying this, it confirms, that I´ve always the newest version - it
is updating automatically.

[image: image.png]


After it..trying to  make altus "run", it´s inviting me to disconnect..
only option:


[image: image.png]


after it a "neverending story" of the try to disconnect.. but does´nt work


[image: image.png]


switching on again, 1 account has to be connected from the beginning - the
other one is trying.. but does´nt work.. ending with the same invitation to
disconnect, that I already described in the beginning.



[image: image.png]


and the other one has the same problem


Do you have any idea or recommendation for me what I can do, for that..
after 1 time connecting.. it´s always remembering entering the next time
(like it was always in the past)??


As I appreciate and use Altus so much.. and as it seems there is no similar
programm exisiting.. I would appreciate so much to have it again, like it
has always been.

Are you already familiar with this problem?



Kind regards



Matthias





Am Fr., 8. Apr. 2022 um 17:26 Uhr schrieb Aman Harwara <
***@***.***>:

**Comment by Ax3lA** [comment]
Hi Matthias,
Hi Aman Harwara,

as he mentioned - nice tool.
I've got a similiar issue, but I'm helping me out by disconnecting the accounts from Altus and from the smartphones. Afterwards I reconnect by using the QR-code. Sometimes it also does help my by restarting the Altus-tool, because from autostart it is stuck also sometimes.

But my setup is a bit different, so maybe it will help to improve Altus.

I copied this from the About inside the help menue.
Altus: 4.5.6
  Electron: 16.0.7
  Chrome: 96.0.4664.110
  V8: 9.6.180.21-electron.0
  OS: Windows_NT x64 10.0.19044

I am not using Chrome, but I have it installed as PortableApp, because I like the usage of moving folder to a new installed Computer and you have all your tools already installed and usable in notime. And I think that the registry keeps cleaner, because no setup routine is running ;-)
```
About Chrome shows:
Version 100.0.4896.75 (Offizieller Build) (32-Bit)
```

It doesn't match, but at the moment Altus is running fine with accounts (WhatsApp "normal" and "business").

I checked Microsofts Edge browser because it looks like googles Chrome.
```
About Edge shows:
Version 100.0.1185.39 (Offizielles Build) (64-Bit)
```

Whatever, anyway.
I can not tell which Chrome-Version or lets say instance Altus is recognizing in my case.
Maybe it does not find the chrome.exe somehow.

So my suggestion is:
Maybe it could help showing Altus where the chrome.exe can be found (as a setting). Sometimes other tools offer the same possibility.
I am not a programmer, but I can imagine if you put a variable instead a static default path which is good for the most installations.
But maybe you also find Chrome through a registry entry (which in my case maybe does not exist).
I think that this manual setting by the user, choosing the path to the chrome.exe, should solve the problem and a missing chrome message shouldn't appear no longer.

As I understand Altus uses chrome like a little browser with some own GUI for the WhatsApp profile tabs.

By trying to update Altus to the newer version it failed, maybe because I also moved Altus away from the default installation path to my own "_PortableApps" folder ;-).

![grafik](https://user-images.githubusercontent.com/103503203/162950489-701c350b-52e8-45d9-9e36-97f7f524ded6.png)

The error is (I type it again, because I also can't see the pictures from Matse):
```
Cannot find package 'node-fetch' imported from c:\[MyPortableAppsPath]\Altus\ressources\app.asar\src\util\getReleases.js
Did you mean to import node-fetch/src/index.js?
```
And it just offers the OK button.

But that is not the major problem, I reinstall it with the newer version and move it to my PortableApps-folder manually and I guess it'll be fine then.

Hopefully that helps and happy easter ;-)

Best regards
Alexa

**Comment by Matse1968** [comment]
Thank you so much for all your effort to help.
IMAGINE :o)
Suddenly it works.
Don´t have any explanation for it ...
With computers sometimes it is like that... Miracles happen.
Or maybe they just fixed the problem.

Thank you again

Matthias



Liebe Grüße



Matthias Woeste

Mail: ***@***.***




Am Fr., 8. Apr. 2022 um 20:34 Uhr schrieb Matthias Woeste ***@***.***

**Comment by Ax3lA** [comment]
Hey Matthias,

same with me. It worked from the day on I wrote that comment.

However, maybe it could be also something with WhatsApp, after updating that. I haven't checked the WhatsApp Version while it was not working.

I guess the issue can be closed.
But I keep going with my recommendation for the setting to adjust the path to chrome.exe ;-)

Bye @ all
and
frohe Ostern, Matze ;)


@amanharwara 
I'm gonna buy you a coffee.

Best regards
Alex

**Comment by amanharwara** [comment]
Hi Matthias and Alex , sorry for the late reply, but I am aware of this issue (see #179). Unfortunately none of the fixes I've tried so far work consistently. It works perfectly fine for some people and not at all for others.

> Maybe it could help showing Altus where the chrome.exe can be found (as a setting). Sometimes other tools offer the same possibility. [..]
> I am not a programmer, but I can imagine if you put a variable instead a static default path which is good for the most installations. [..]
> As I understand Altus uses chrome like a little browser with some own GUI for the WhatsApp profile tabs.

You are correct here, but Altus doesn't detect and use your installation of Chrome. Instead it supplies its own copy of Chrome using [Electron](https://www.electronjs.org/).

The issue happens because of how WhatsApp detects the browser, using something called the [User Agent string](https://en.wikipedia.org/wiki/User_agent). To fix this, Altus makes sure the user agent looks as close as possible to Chrome's, but even then it becomes necessary to clear the app storage and reload. This in turn causes the WhatsApp linkage to break because of how it works now. Earlier this wasn't an issue, but now due to how WhatsApp stores the data, it breaks.

> I'm gonna buy you a coffee.

@Ax3lA I really appreciate your thought, but I should make it clear that maintaining Altus isn't my first priority anymore, at times I have also thought of archiving the project so I'm not sure how long I can continue working on it. Which is why I think it might be better for you to donate to other open source projects that you use which are probably more deserving of your money.

> By trying to update Altus to the newer version it failed, maybe because I also moved Altus away from the default installation path to my own "_PortableApps" folder ;-).

Hmm, I thought this issue was fixed in v4.6.0. Are you on the latest version?

**Comment by amanharwara** [comment]
I have managed to get somewhat of a fix working in [v4.7.0](https://github.com/amanharwara/altus/releases/tag/4.7.0). Can you try it out?

If you get the "Update Chrome" message, just press "Ctrl+Shift+R" to reload, and it should go away. And your WhatsApp connection should work correctly without needing to logout or re-install Altus. Let me know if that is not the case.

**Comment by amanharwara** [comment]
Actually, try out the newer [v4.7.1](https://github.com/amanharwara/altus/releases/tag/4.7.1) release, where it will auto-reload the page if it detects the "Update Chrome" message.

**Comment by Matse1968** [comment]
Hi Aman,
it works... and not only this.. it also seems to be faster in opening
THANK YOU SO MUCH!!!

Kind regards





Matthias Woeste

Mail: ***@***.***




Am Fr., 15. Apr. 2022 um 13:21 Uhr schrieb Aman Harwara <
***@***.***>:

**Comment by Ax3lA** [comment]
> it will auto-reload the page if it detects the "Update Chrome" message.

Hi @amanharwara 
that program works fine now, but meanwhile I mentioned, that the page is not auto realoading.
If that happens, I use the shortcut "Ctrl+Shift+R" and it works fine.

Thank you a LLLLLot.

I guess you can close that case or mark it as solved.

Cheers.
/Alexa

**Comment by amanharwara** [comment]
Closing this issue as the main issue seems to be solved.

> that the page is not auto realoading.

Does it never auto-reload, or only some times? If it never auto-reloads, maybe create a new issue with any information you might think would be useful in testing this.

**Comment by Matse1968** [comment]
Just to say - THANK YOU VERY MUCH :o)
GREAT what you have done.
Working so well now



Kind



Matthias Woeste





Am Do., 12. Mai 2022 um 21:09 Uhr schrieb Ax3lA ***@***.***>:

**Comment by Matse1968** [comment]
Hello Aman,

Good morning,
a little thing, that I observed in the Altus-Program:
I´m using a lot the "Broadcast" Option of Whats-App.
Sending a message to different recipients at the same time... everybody is
receiving it directly from me privately (in contrast to creating a "group"
in WhtasApp)
In the past it was always possible to use this tool (Broadcast) with Altus
also.
In the updated version, "Broadcasts" are not visible anymore. Is it
possible adjust it, that we can work with "Broadcasts" again?
At the moment I´ve always to work with "copy/paste" und using the mobile to
post finally.
Looking forward for your thoughts

Kind regards

Matthias Woeste





Am Do., 12. Mai 2022 um 21:41 Uhr schrieb Aman Harwara <
***@***.***>:

**Comment by amanharwara** [comment]
@Matse1968 Are you able to see that option on web.whatsapp.com? It's possible that WhatsApp itself disabled that option. That is not something I have control over.

**Comment by Matse1968** [comment]
Thank you Aman,

you are right! I tried whatsapp web...
Not visible anymore also....

Thank you!!


Have a nice day



Matthias Woeste

Mail: ***@***.***




Am Fr., 10. Juni 2022 um 09:23 Uhr schrieb Aman Harwara <
***@***.***>:
