### ISSUE TITLE
No tray icon in ubuntu 18.04

### ISSUE THREAD

**Issue by dCo3lh0** [amanharwara/altus#23]
Hi, it seems like the icon on tray don't show at all in my linux mint 19.1 (xfce - gnome based) (ubuntu 18.04 based), another thing i miss in the app is the close to tray option, so if i minimize or close the app, it just get out of taskbar, but keeps running with the tray icon. Thanks!

**Comment by ShadyThGod** [comment]
This is something that has me scratching my head for a long time. There are issues related to the tray icon on Linux distributions in Electron itself, due to which I have not been able to fix it properly. This is why I have put the "help wanted" label; I can't seem to find a fix, maybe someone else can.

**Comment by derdjme** [comment]
I found this here: https://discourse.appimage.org/t/appimage-does-not-show-icon-in-task-bar/40/5

**Comment by banchaa** [comment]
Yes, it propably has something to do with AppImages. I notice when I close the application under KDE Plasma with Debian, that a hidden placeholder is being moved in the tray bar.

Thumbs up so far. I was not able to find Altus without searching explicit for "electron app with whatsapp". That is a nice piece of application.

**Comment by ShadyThGod** [comment]
I've removed the tray icon feature and setting on Linux since v3.0 as it doesn't work properly anyways. I'm also closing this issue until there are any new developments. If you have any fix for this, let me know.

**Comment by insign** [comment]
I disagree with the closing of this issue since it is "help wanted".

**Comment by amanharwara** [comment]
I closed it because there isn't really any fix for this that can be implemented by changing Altus' code. I've researched a bit and the issue actually is stemming from Chromium itself, so there's not really much that can be done in Altus to fix it other than waiting for an Electron update that patches this.

**Comment by amanharwara** [comment]
Just read an issue thread on the electron repo. I think there might be a fix for this. I'll re-open it till then.

**Comment by davidrhoderick** [comment]
Just confirming my interest in this and that it doesn't show up in Pop!_OS 20.04.

**Comment by MarceloZapatta** [comment]
#77 Should be fixed with this PR

**Comment by amanharwara** [comment]
Merged #77. Will publish a release soon.
Thanks @MarceloZapatta!

**Comment by amanharwara** [comment]
Closing this issue since it should be fixed.
