### ISSUE TITLE
Can't install on Windows 7

### ISSUE THREAD

**Issue by JoseHidalgo** [amanharwara/altus#240]
Hi. Title says all. Altus-Setup-4.8.6.exe just won't execute on my Windows 7 PC. Every time I double-click on the installer, the process will fail. I don't even see it in task manager. I don't understand what's happening.

I'd like to install Altus because WhatsApp Desktop is forcing its users to migrate to Windows 10/11 (with the MS Store) and the desktop client will stop functioning in 22 days.

![2023 06 04 - 03 04 58](https://github.com/amanharwara/altus/assets/10851603/1648ba6b-ef9d-4d2f-871b-119e564a792d)

I can't afford to migrate to Windows 11 right now. I have to wait until september at least. Which is why I need a solution right now.

Why can't Altus work on Windows 7? Thanks.

**Comment by sk8rthug** [comment]
Altus works fine on Win7. For some reason you have problems with the installer. I dunno. Check its size - it should be 132 MB (138 464 232 bytes). Try running it as administrator. Or in a safe mode as a drastic measure :D

**Comment by Gabarito007** [comment]
I second that.
I use Windows 7 and it installs fine.
Ultimate SP1 64 bits. No problem here.

**Comment by JoseHidalgo** [comment]
Thanks guys, I'm glad to know that.
Now I only have to find why Altus installer won't work on my particular Win 7 x64 SP1.
The installer is fine, I have downloaded it twice.
Running it as admin changes nothing.
I'll check safe mode.

**Comment by Gabarito007** [comment]
What error messages you got?
Process fails, but how it happens?
Capture prints? Any?

You can't see it on Task Manager maybe because it executes and closes quickly.
Running as Safe Mode I guess it isn't  an option.

**Comment by Gabarito007** [comment]
Try run Process Monitor before start installation and look for errors.
Latest Process Monitor won't run on Windows 7. You have to download this version:

https://portableapps.com/news/2019-03-27--process-monitor-portable-3.52-released

Also, make some integrity checks of your system. CCleaner has a tool to check Registry inconsistencies.
Do you have all Microsoft Visual C++ redist packs installed?
DotNET too?

Too many things may be the source of your problem.

Try to solve that, because Altus is superb!
No more WhatsApp Desktop's terrors about to stop the use of the program.

**Comment by Gabarito007** [comment]
I'm not an expert in Process Monitor.
We do need that person to analyse your log properly.

I could see some "Name colision" in it, but I guess this isn't the source of the problem.
But there are too many "Name not found" among Registry entries.
This key is the last one before threads going exit:

`HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\explorer\FolderDescriptions\{5cd7aee2-2219-4a67-b85d-6c9ce15660cb}`

Do you have this key in your Registry?
My Registry has this key.

I cannot get a log file, to compare to yours, because I've already installed the program.
And don't want to be exposed to the risk to have some error if I uninstall and try to install again.


Whats happens when Setup fails? Any error message?
As you can see, I already ask that:

> What error messages you got? Process fails, but how it happens? Capture prints? Any?
> 

All informations you could give is the best to diagnose the problem.

Also, make some integrity checks of your system. CCleaner has a tool to check Registry inconsistencies.

**Comment by JoseHidalgo** [comment]
Yes, I have that key indeed:

![2023 06 08 - 02 58 12](https://github.com/amanharwara/altus/assets/10851603/402af909-b8bf-4729-a0f6-fd92c2045c1f)

As for the rest, I have absolutely no error messages and no trace at all in the Task Manager. It's exactly like the process never launched... when Process Manager shows us that it did. First time I thought I hadn't clicked well on the icon.

About integrity checks, I'd prefer not to mess with my system. Like I said, this system has to function until september. Right now it's perfectly stable (has been for years actually), and registry cleaners are not always a good thing.

That's all I have for the moment. But the log should be enough (for an expert of course) to understand what's going on.

**Comment by sk8rthug** [comment]
I know it was a stupid suggestion, but still - try safe mode. Also, if you have non-english letters in the path from where you launch the isntaller, try launching it from the root of a disk. And if you have anti-virus, try turning it off.

**Comment by Gabarito007** [comment]
Good suggestions! Unicode characters along the path and/or Registry keys.
Or very long path, above 128 characters...

**Comment by JoseHidalgo** [comment]
Thanks guys. And there are NO stupid suggestions. :)
- Tried launching from D:\ AND with antivirus completely off : same issue (I didn't have any non-english letters in my previous path, but still)
- I'll try safe mode whenever I can reboot, which isn't possible for the moment. I'll report back.

**Comment by sk8rthug** [comment]
Have you tried turning it off and on again? :D

**Comment by nanoflooder** [comment]
@JoseHidalgo Does the Altus itself work on your system? Here's the unpacked 64-bit version from the latest installer: https://mega.nz/file/xMgRRQDY#Pi9r2n8FJZDsBWyUP7-sojV0UbT2NCnQCIgbfPbcuMY

**Comment by JoseHidalgo** [comment]
Hi @nanoflooder , thank you so much! Sorry for the delay, I was away.

I can confirm that Altus works perfectly on my system from the unpacked 64-bit version. So whatever my issue was, it was definitely installer-related (or system-related, but in relation to the installer, not to the app itself).

I have also installed other apps during that time without issues. It's only Altus installation which was a problem.

Altus works nicely. I can feel it's a bit slower (less reactive) than the native app, but that's normal due to its nature I guess, plus I have an old rig (on a new rig probably I wouldn't notice the difference). For me it's definitely good enough, and it will nicely replace the native app once it stops functioning on my system. I couldn't be more satisfied. :)

I can also confirm that I haven't rebooted my PC since last time. It has running processes most of the time. ;p

**Comment by Gabarito007** [comment]
Glad to know that you could solve your problem!
User nanoflooder had a very good idea about to try the unpacked version.

So, installer was the problem.
Hummm!

Altus replace totally the native WhatsApp app.
Good luck.

**Comment by sk8rthug** [comment]
Now I'm sure simple reboot would solve the installation problem. I suppose you still should install it properly for the correct work of the settings.

**Comment by JoseHidalgo** [comment]
Yes, it's probably a reboot thing. I will try a proper install when I can. Thanks to everybody for being so helpful: this was a perfect support thread. :)
