### ISSUE TITLE
How to avoid Whatsapp ban?

### ISSUE THREAD

**Issue by MiaBCN** [amanharwara/altus#247]
Dear amanharwara,

first of all, thank you for the amazing tool, it is really helpful!

Do you know any reasons why Whatsapp could ban some of the linked Whatsapp accounts? It happens when I try to connect a new device to Altus, then the account gets banned a few moments later. However, the existing and linked accounts still stay connected and are not getting banned..

Do you have any idea what the reason for that could be and how this could be avoided? Could it be that the IP-Adress of my Altus device (laptop) might be a problem?

Thank you in advance for any help and any reccomendation!:)

Best regards,
Mia

**Comment by amanharwara** [comment]
Hello, this isn't a bug. Why WhatsApp would ban any account is only known to WhatsApp. For what it's worth, I haven't really heard anyone else being banned just for using Altus. That is always a risk when using third-party clients, ultimately WhatsApp makes the decision. But Altus is for the most part pretty safe since it doesn't do anything against WhatsApp ToS (at least that i know of) and only does basic customization like theming. There is a chance that maybe they don't like having multiple accounts on the same device, but I no way of knowing whether that's actually the case.
Atlus does not and will not implement anything that allows avoiding/evading bans.

**Comment by amanharwara** [comment]
If you're really not doing anything that might against WhatsApp's terms of service, I would recommend sticking to using the official web or desktop client.
