### ISSUE TITLE
[Feature Request] Bypassing WhatsApp's inability to set a local profile pic for some friends

### ISSUE THREAD

**Issue by JoseHidalgo** [amanharwara/altus#265]
Hello. As [officially said by WhatsApp](https://faq.whatsapp.com/1142548356683482), users have a limited control about their own friend pictures, even locally:
- If a friend has set his own WhatsApp profile pic, then apparently you can bypass it by setting a local profile pic in your Contacts app
- However, if a friend hasn't set his own WhatsApp profile pic, or if he has set its visibility to nobody, there's no way you can still set a local profile pic for that friend. On your own phone!

I think that's ridiculous. We should be able to set contacts pics to some of our friends, locally. At least when they don't have one on WhatsApp!

In my particular case, I have one of my best friends who has decided to not set any WhatsApp picture. That is of course his decision and I own't ask him to do otherwise. So I have set a local custom pic in my Contacts app, and that works perfectly of course. But that pic isn't displayed in WhatsApp because WhatsApp doesn't want to, and of course there's nothing I can do about it.

However, maybe that pic could be at least displayed in Altus. It would make my day, since this is a friend who I talk to quite often, and it bothers me to be unable to see a pic among all my other contacts.

I know Altus is a WhatsApp web wrapper, so it displays what WhatsApp web displays. But Altus is more than that. It has some unique features. So I maybe it's technically possible to make Altus display a custom local pic for a given friend. Just like our Contacts app allows us to on our phones.

It could be a "quick and dirty hack". For example:
- Have the user select the problematic contact in Altus (see the attached picture),
- Have the user select a local custom pic,
- Display that custom pic as an overlay to that contact's "no picture" picture.

Of course other issues have to be managed: scrolling, window resizing, etc. Maybe it's not that easy. I don't know. But even something that works "80% of the time" would be enough for me.

Could this be done in a future Altus version? Thanks in advance! :)

![2024 01 06 - 17 38 02](https://github.com/amanharwara/altus/assets/10851603/3989e7c7-62a9-41e3-8925-6229407903e1)

**Comment by JoseHidalgo** [comment]
... no reply at all ? @amanharwara maybe ?... Thank you.

**Comment by amanharwara** [comment]
This will have to be a no from me.

It would require too much effort to initially implement and then maintain. Because of the nature of how it would have to be implemented, it would also be very easily breakable from a change on WhatsApp's end. It is also a very bespoke feature as opposed to something more people have requested where it would make sense to put time and effort into that.

Also, I'm also not really going to accept any PR for this because even if someone else does initially implement this, there is no guarantee that they will then continue to maintain it if something breaks and that maintenance burden will come onto me.

Hope you can understand :)
