### ISSUE TITLE
Theme visual issues & settings issues

### ISSUE THREAD

**Issue by Squar3wave** [amanharwara/altus#65]
Hello! I have been using Altus since i couple of weeks and really like it. 
I am currently on Ubuntu 16.04 for work reasons, so a system upgrade is not currently an option. 

I have two issues:

1) I can't change the settings. if, for example, i toggle off the prompt menu when exiting and click save, the save box changes into a loading wheel and never stops.

![image](https://user-images.githubusercontent.com/66468409/83862180-df47b780-a721-11ea-9781-d9c13cf15dc3.png)

2) Since today the dark theme is mixed with elements of the light theme, making it somewhat uncomfortable. (e.g. the response box is from the light theme and the search bar too).

Here is a screenshots, heavily censored for my contacts privacy

![censurato](https://user-images.githubusercontent.com/66468409/83862090-c7703380-a721-11ea-97c1-57b2514d1752.png)

What can be done? Is it fixable? Thanks in advance!

**Comment by amanharwara** [comment]
1. Can you tell me what version of Altus are you using?

2. Altus uses the [dark-whatsapp](https://github.com/vednoc/dark-whatsapp) theme for dark mode. Probably due to changes in WhatsApp's code, the theme is broken. I can't guarantee how quickly that'll be fixed, but what you can do is periodically is press `Ctrl+T` or manually open the **Theme Manager** and click "Update Base Themes". This will fetch any update to the theme if there is one.

**Comment by Squar3wave** [comment]
Hello. I am using v3.11.0

i tried your suggestion and it didn't work. I suspect that the app is not really checking for updates, since when i press "update base themes" the wheel doesn't fully rotate but just tilts a little.

**Comment by Squar3wave** [comment]
Also, i forgot to mention. The problem applies even when i try to create a custom theme.

**Comment by amanharwara** [comment]
> i tried your suggestion and it didn't work. I suspect that the app is not really checking for updates, since when i press "update base themes" the wheel doesn't fully rotate but just tilts a little.

It is checking for updates, it's probably that the theme hasn't been updated yet. (I checked, and the latest update to the theme was 5 days ago.) So till then you might want to disable the dark theme.

> so, i forgot to mention. The problem applies even when i try to create a custom theme.

Yes, that's because it uses the dark theme as it's base.

> I am using v3.11.0

Is that a fresh install or did you update from a previous installation?

**Comment by Squar3wave** [comment]
I downloaded the client anew. But I didn't purge old settings as it started again from the old version's.

**Comment by amanharwara** [comment]
> I downloaded the client anew. But I didn't purge old settings as it started again from the old version's.

Delete this folder: `~/.config/altus` and run the program again.
It will get rid of the current settings and return to default. The issue maybe resided due to some previous fault in the settings maybe.

**Comment by Squar3wave** [comment]
Done, however both issues remain. For the dark theme i will follow your suggestion and check daily for updates, for the settings what can i do?

**Comment by amanharwara** [comment]
Do the settings not actually update or is it just a visual bug?

**Comment by Squar3wave** [comment]
Settings don't update

**Comment by amanharwara** [comment]
Hmm that's weird. Settings seem to be working fine on my Linux machine.

**Comment by Squar3wave** [comment]
Maybe it's a problem strictly with Ubuntu 16.04?

**Comment by amanharwara** [comment]
I tried on my Linux machine again and it looks like it's not specific to Ubuntu.

**Comment by amanharwara** [comment]
Found what was causing the issue. I'll release a fix by tomorrow.

**Comment by Squar3wave** [comment]
Thanks a lot!

**Comment by Squar3wave** [comment]
Hi, just checking in to say that the Dark theme issue has been resolved. I just tried updating the themes and now everything is a-ok. Again, thanks for your time!

**Comment by amanharwara** [comment]
[v3.11.1](https://github.com/amanharwara/altus/releases/tag/3.11.1)

- This fixes the settings bug.
- There are now two options for dark mode. One is the official dark mode by WhatsApp which is the one that will be used when you select the "`Dark`" theme. The other is the better-looking one ([dark-whatsapp](https://github.com/vednoc/dark-whatsapp)) which can be used by selecting "`Dark Plus`" as the theme.
   * Since the "`Dark`" theme is the official dark theme by WhatsApp, it probably won't break ever. However, I must say, it doesn't look as good as the "`Dark Plus`" theme.
   * The "`Dark Plus`" theme looks much better than the official one, but since it's not official, it has more chances of breaking.

P.S.: If you can't find the "`Dark Plus`" option:
1. Open Theme Manager (or press `Ctrl+T`)
2. Click on "`Update Base Themes`" and wait for a few seconds.
3. Click on reload button or press `Ctrl+Shift+R`
4. Close the Theme Manager and reload the app again using `Ctrl+Shift+R`

**Comment by Squar3wave** [comment]
Works perfectly! Once again, thank you very much!
